// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiXEj_rkxYumZv773tbFvH_C-lC5haHoU',
    appId: '1:180824158614:web:fefca0105e629f55cdedb7',
    messagingSenderId: '180824158614',
    projectId: 'soul-cypher',
    authDomain: 'soul-cypher.firebaseapp.com',
    storageBucket: 'soul-cypher.appspot.com',
    measurementId: 'G-SCT3WJMDL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP39aOmiesEU9lkFvEbjY1UDMvVqacR9E',
    appId: '1:180824158614:android:6650ad6347dc7bf5cdedb7',
    messagingSenderId: '180824158614',
    projectId: 'soul-cypher',
    storageBucket: 'soul-cypher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB17SRDn2gZvOkryIULx5c-nQPs3EaSnH0',
    appId: '1:180824158614:ios:4a2732665275d099cdedb7',
    messagingSenderId: '180824158614',
    projectId: 'soul-cypher',
    storageBucket: 'soul-cypher.appspot.com',
    iosBundleId: 'com.example.soulcypher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB17SRDn2gZvOkryIULx5c-nQPs3EaSnH0',
    appId: '1:180824158614:ios:4a2732665275d099cdedb7',
    messagingSenderId: '180824158614',
    projectId: 'soul-cypher',
    storageBucket: 'soul-cypher.appspot.com',
    iosBundleId: 'com.example.soulcypher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiXEj_rkxYumZv773tbFvH_C-lC5haHoU',
    appId: '1:180824158614:web:0a5952bac515d0bccdedb7',
    messagingSenderId: '180824158614',
    projectId: 'soul-cypher',
    authDomain: 'soul-cypher.firebaseapp.com',
    storageBucket: 'soul-cypher.appspot.com',
    measurementId: 'G-97N69XMRX3',
  );
}
